name: Release dexsearch

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build jar with Gradle
        run: ./gradlew jar

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/libs/dexsearch-latest.jar
            clientlib/build/libs/clientlib-latest.jar